import { Router } from 'express';
import { z } from 'zod';
import prisma from '../lib/prisma.js';
import { requireAuth, requireRole, loadOwnProfile } from '../middleware/auth.js';
import { validateBody } from '../middleware/validate.js';
import { asyncHandler } from '../middleware/errorHandler.js';
import { idempotency } from '../middleware/idempotency.js';
import { generateProposals, buildFeasibleSpace, SLOT_WEIGHTS } from '../services/scheduling.service.js';
import { rankInterviewers, MATCH_WEIGHTS } from '../services/matching.service.js';
import { confirmProposal } from '../services/orchestration.service.js';
import { callAiService } from '../providers/aiClient.js';
import { auditFromRequest } from '../services/audit.service.js';
import { parseArray, stringifyJson } from '../lib/json.js';
import { badRequest, notFound, forbidden } from '../lib/errors.js';
import { AUDIT_ACTIONS, ROLES } from '../../../shared/constants.js';
import { getSettings } from '../services/settings.service.js';
import { SETTING_KEYS } from '../../../shared/constants.js';

const router = Router();
router.use(requireAuth);

/**
 * Generate ranked slot proposals for a request.
 * This is the Schedule Builder's main call.
 */
router.post(
  '/generate',
  requireRole(ROLES.RECRUITER, ROLES.ADMIN),
  idempotency(),
  validateBody(
    z.object({
      requestId: z.string().min(5),
      persist: z.boolean().default(true),
    })
  ),
  asyncHandler(async (req, res) => {
    const started = Date.now();
    const result = await generateProposals(req.body.requestId, { persist: req.body.persist });

    await auditFromRequest(req, {
      action: AUDIT_ACTIONS.SLOTS_GENERATED,
      entity: 'InterviewRequest',
      entityId: req.body.requestId,
      summary: `${result.proposals.length} slot(s) generated by ${result.engineUsed} from ${result.feasibleSlotCount} feasible options`,
      metadata: {
        engine: result.engineUsed,
        durationMs: Date.now() - started,
        topScore: result.proposals[0]?.score,
        eligibleInterviewers: result.matching.eligible.length,
      },
    });

    if (result.proposals[0]) {
      await auditFromRequest(req, {
        action: AUDIT_ACTIONS.SLOT_RECOMMENDED,
        entity: 'InterviewRequest',
        entityId: req.body.requestId,
        summary: `Recommended ${result.proposals[0].localLabels.candidate} (score ${result.proposals[0].score})`,
        metadata: { reasons: result.proposals[0].reasons, interviewers: result.proposals[0].interviewers.map((i) => i.name) },
      });
    }

    res.json({
      ...result,
      weights: { slot: SLOT_WEIGHTS, interviewer: MATCH_WEIGHTS },
      generatedInMs: Date.now() - started,
    });
  })
);

/** Interviewer recommendations only - used by the Schedule Builder's left pane. */
router.post(
  '/match-interviewers',
  requireRole(ROLES.RECRUITER, ROLES.ADMIN),
  validateBody(z.object({ requestId: z.string().min(5), limit: z.coerce.number().min(1).max(30).default(10) })),
  asyncHandler(async (req, res) => {
    const request = await prisma.interviewRequest.findUnique({
      where: { id: req.body.requestId },
      include: { application: { include: { candidate: { include: { user: true } }, job: true } } },
    });
    if (!request) throw notFound('Interview request not found');

    const result = await rankInterviewers({
      request,
      rangeStart: new Date(Math.max(+new Date(request.earliestUtc), Date.now())),
      rangeEnd: new Date(request.latestUtc),
      limit: req.body.limit,
    });

    await auditFromRequest(req, {
      action: AUDIT_ACTIONS.INTERVIEWERS_MATCHED,
      entity: 'InterviewRequest',
      entityId: request.id,
      summary: `${result.ranked.length} eligible interviewer(s) ranked (${result.rejected.length} filtered out)`,
      metadata: { top: result.ranked.slice(0, 3).map((r) => ({ name: r.name, score: r.matchScore })) },
    });

    res.json({
      ...result,
      ranked: result.ranked.map((r) => ({
        ...r,
        // Free windows are large; the UI only needs the count here.
        freeWindows: undefined,
        preferredWindows: undefined,
        freeWindowCount: r.freeWindows.length,
      })),
    });
  })
);

/** Dry run: show the feasible space and every hard-constraint check. */
router.post(
  '/preview',
  requireRole(ROLES.RECRUITER, ROLES.ADMIN),
  validateBody(z.object({ requestId: z.string().min(5) })),
  asyncHandler(async (req, res) => {
    const request = await prisma.interviewRequest.findUnique({
      where: { id: req.body.requestId },
      include: {
        application: {
          include: { job: true, candidate: { include: { user: true, skills: { include: { skill: true } } } } },
        },
      },
    });
    if (!request) throw notFound('Interview request not found');

    const space = await buildFeasibleSpace(request);
    res.json({
      diagnostics: space.diagnostics,
      feasibleSlotCount: space.slots.length,
      firstSlots: space.slots.slice(0, 10).map((s) => ({ start: s.start, end: s.end, eligibleCount: s.eligible.length })),
      eligibleInterviewers: (space.interviewers || []).map((i) => ({ id: i.interviewerId, name: i.name, matchScore: i.matchScore })),
      rejected: space.matching?.rejected ?? [],
      candidateFreeWindows: space.candidateAvail?.free ?? [],
    });
  })
);

/** Confirm a proposal -> creates the interview (the transactional path). */
router.post(
  '/confirm',
  idempotency(),
  validateBody(z.object({ proposalId: z.string().min(5), note: z.string().max(500).optional() })),
  asyncHandler(async (req, res) => {
    const proposal = await prisma.slotProposal.findUnique({
      where: { id: req.body.proposalId },
      include: { request: { include: { application: true } } },
    });
    if (!proposal) throw notFound('Slot proposal not found');

    // Candidates may only accept proposals for their own application.
    if (req.user.role === ROLES.CANDIDATE) {
      const own = await loadOwnProfile(req);
      if (proposal.request.application.candidateId !== own?.id) {
        throw forbidden('This proposal is not for you');
      }
    } else if (![ROLES.RECRUITER, ROLES.ADMIN].includes(req.user.role)) {
      throw forbidden('Only a recruiter or the candidate can confirm a slot');
    }

    const interview = await confirmProposal({
      proposalId: req.body.proposalId,
      actor: req.user,
      // Candidate self-booking counts as their acceptance.
      autoConfirmCandidate: req.user.role === ROLES.CANDIDATE,
      reason: req.body.note,
    });

    res.status(201).json(interview);
  })
);

/** Regenerate proposals for a request after a change (e.g. reschedule request). */
router.post(
  '/reschedule',
  requireRole(ROLES.RECRUITER, ROLES.ADMIN),
  idempotency(),
  validateBody(z.object({ requestId: z.string().min(5), excludeInterviewId: z.string().optional() })),
  asyncHandler(async (req, res) => {
    const result = await generateProposals(req.body.requestId, {
      excludeInterviewId: req.body.excludeInterviewId,
    });
    await auditFromRequest(req, {
      action: AUDIT_ACTIONS.SLOTS_GENERATED,
      entity: 'InterviewRequest',
      entityId: req.body.requestId,
      summary: `Re-generated ${result.proposals.length} slot(s) after a reschedule request`,
    });
    res.json(result);
  })
);

/** Current scoring policy - what the numbers on screen actually mean. */
router.get(
  '/weights',
  asyncHandler(async (_req, res) => {
    res.json({
      slotObjective: SLOT_WEIGHTS,
      interviewerMatch: MATCH_WEIGHTS,
      note:
        'Hard constraints are enforced in the backend before optimisation; these weights only order the feasible options.',
    });
  })
);

/** Open proposals for a request (used to re-render the builder without recomputing). */
router.get(
  '/proposals/:requestId',
  asyncHandler(async (req, res) => {
    const rows = await prisma.slotProposal.findMany({
      where: { requestId: req.params.requestId },
      orderBy: [{ status: 'asc' }, { rank: 'asc' }],
    });
    const ids = [...new Set(rows.flatMap((r) => r.interviewerIdsCsv.split(',').filter(Boolean)))];
    const profiles = await prisma.interviewerProfile.findMany({
      where: { id: { in: ids } },
      include: { user: { select: { name: true, timezone: true } } },
    });
    const byId = new Map(profiles.map((p) => [p.id, p]));

    res.json(
      rows.map((r) => ({
        id: r.id,
        rank: r.rank,
        startUtc: r.startUtc,
        endUtc: r.endUtc,
        score: r.score,
        riskScore: r.riskScore,
        status: r.status,
        engineUsed: r.engineUsed,
        expiresAt: r.expiresAt,
        reasons: parseArray(r.reasonsJson),
        breakdown: JSON.parse(r.breakdownJson || '{}'),
        interviewers: r.interviewerIdsCsv
          .split(',')
          .filter(Boolean)
          .map((id) => ({ id, name: byId.get(id)?.user.name, title: byId.get(id)?.title, timezone: byId.get(id)?.user.timezone })),
      }))
    );
  })
);

export default router;
