/**
 * Shared vocabulary for backend + frontend.
 *
 * The Prisma schema stores these as plain strings (portability contract, see
 * docs/ARCHITECTURE.md §6). This file is the single source of truth that both
 * the API validators (zod) and the UI use, so an invalid value can never be
 * written by the application layer.
 */

export const ROLES = Object.freeze({
  RECRUITER: 'RECRUITER',
  CANDIDATE: 'CANDIDATE',
  INTERVIEWER: 'INTERVIEWER',
  ADMIN: 'ADMIN',
});
export const ROLE_VALUES = Object.values(ROLES);

export const INTERVIEW_TYPES = Object.freeze({
  TECHNICAL: 'TECHNICAL',
  CODING: 'CODING',
  SYSTEM_DESIGN: 'SYSTEM_DESIGN',
  MANAGERIAL: 'MANAGERIAL',
  HR: 'HR',
});
export const INTERVIEW_TYPE_VALUES = Object.values(INTERVIEW_TYPES);

export const INTERVIEW_TYPE_LABELS = Object.freeze({
  TECHNICAL: 'Technical',
  CODING: 'Coding',
  SYSTEM_DESIGN: 'System Design',
  MANAGERIAL: 'Managerial',
  HR: 'HR',
});

export const INTERVIEW_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED',
  NO_SHOW: 'NO_SHOW',
});
export const INTERVIEW_STATUS_VALUES = Object.values(INTERVIEW_STATUS);
/** Statuses that still occupy a person's calendar. */
export const ACTIVE_INTERVIEW_STATUSES = Object.freeze([
  INTERVIEW_STATUS.SCHEDULED,
  INTERVIEW_STATUS.CONFIRMED,
  INTERVIEW_STATUS.IN_PROGRESS,
]);

export const REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROPOSED: 'PROPOSED',
  /** An offer is out with an interviewer; the candidate's slots are held. */
  WAITING: 'WAITING',
  /** Nobody could take the candidate's times - they now pick from ours. */
  SLOTS_OFFERED: 'SLOTS_OFFERED',
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
});
export const REQUEST_STATUS_VALUES = Object.values(REQUEST_STATUS);

export const CANDIDATE_RESPONSE = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  RESCHEDULE_REQUESTED: 'RESCHEDULE_REQUESTED',
});

/** Lifecycle of a single "will you take this slot?" offer to an interviewer. */
export const OFFER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  EXPIRED: 'EXPIRED',
});
export const OFFER_STATUS_VALUES = Object.values(OFFER_STATUS);

/** How long an interviewer has to answer an offer before it passes on. */
export const OFFER_RESPONSE_HOURS = 12;

/** How many interviewers an offer walks down before the candidate re-picks. */
export const OFFER_MAX_RANK = 2;

export const PANEL_RESPONSE = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
});

export const AVAILABILITY_KIND = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  PREFERRED: 'PREFERRED',
  UNAVAILABLE: 'UNAVAILABLE',
});
export const AVAILABILITY_KIND_VALUES = Object.values(AVAILABILITY_KIND);

export const INCIDENT_TYPES = Object.freeze({
  INTERVIEWER_DECLINED: 'INTERVIEWER_DECLINED',
  INTERVIEWER_UNAVAILABLE: 'INTERVIEWER_UNAVAILABLE',
  CANDIDATE_CANCELLED: 'CANDIDATE_CANCELLED',
  CANDIDATE_NO_SHOW: 'CANDIDATE_NO_SHOW',
  RESCHEDULE_REQUESTED: 'RESCHEDULE_REQUESTED',
  INTERVIEW_OVERRUN: 'INTERVIEW_OVERRUN',
  MEETING_LINK_FAILURE: 'MEETING_LINK_FAILURE',
  CALENDAR_SYNC_FAILURE: 'CALENDAR_SYNC_FAILURE',
  SCHEDULING_CONFLICT: 'SCHEDULING_CONFLICT',
  INTERVIEWER_OVERLOAD: 'INTERVIEWER_OVERLOAD',
  CASCADE_DELAY: 'CASCADE_DELAY',
  UNCONFIRMED_IMMINENT: 'UNCONFIRMED_IMMINENT',
});
export const INCIDENT_TYPE_VALUES = Object.values(INCIDENT_TYPES);

export const INCIDENT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  ANALYZING: 'ANALYZING',
  AWAITING_APPROVAL: 'AWAITING_APPROVAL',
  RECOVERING: 'RECOVERING',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
  FAILED: 'FAILED',
});

export const SEVERITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

export const RISK_LEVEL = Object.freeze({ LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH' });
export const RISK_ORDER = Object.freeze({ LOW: 1, MEDIUM: 2, HIGH: 3 });

export const RECOVERY_STRATEGY = Object.freeze({
  REPLACE_INTERVIEWER: 'REPLACE_INTERVIEWER',
  SHIFT_TIME: 'SHIFT_TIME',
  RESCHEDULE_SLOT: 'RESCHEDULE_SLOT',
  REDUCE_PANEL: 'REDUCE_PANEL',
  REGENERATE_MEETING: 'REGENERATE_MEETING',
  RETRY_SYNC: 'RETRY_SYNC',
  NOTIFY_ONLY: 'NOTIFY_ONLY',
  CANCEL_AND_REQUEUE: 'CANCEL_AND_REQUEUE',
});

/**
 * AUTONOMY POLICY - which recovery strategies the system may apply on its own.
 * Anything above the configured ceiling needs a human decision. This table is
 * what makes "self-healing" safe and explainable rather than a black box.
 */
export const STRATEGY_RISK = Object.freeze({
  NOTIFY_ONLY: RISK_LEVEL.LOW,
  RETRY_SYNC: RISK_LEVEL.LOW,
  REGENERATE_MEETING: RISK_LEVEL.LOW,
  REPLACE_INTERVIEWER: RISK_LEVEL.LOW, // equivalent-skill swap, same time slot
  REDUCE_PANEL: RISK_LEVEL.MEDIUM,
  SHIFT_TIME: RISK_LEVEL.MEDIUM, // same day, small move -> candidate is told
  RESCHEDULE_SLOT: RISK_LEVEL.HIGH, // different day -> recruiter approval
  CANCEL_AND_REQUEUE: RISK_LEVEL.HIGH,
});

export const NOTIFICATION_TYPES = Object.freeze({
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  INTERVIEW_CONFIRMED: 'INTERVIEW_CONFIRMED',
  INTERVIEW_RESCHEDULED: 'INTERVIEW_RESCHEDULED',
  INTERVIEW_CANCELLED: 'INTERVIEW_CANCELLED',
  INTERVIEWER_ASSIGNED: 'INTERVIEWER_ASSIGNED',
  INTERVIEWER_REPLACED: 'INTERVIEWER_REPLACED',
  INTERVIEW_REMINDER: 'INTERVIEW_REMINDER',
  SLOTS_PROPOSED: 'SLOTS_PROPOSED',
  SLOT_OFFER_RECEIVED: 'SLOT_OFFER_RECEIVED',
  SLOTS_UNAVAILABLE: 'SLOTS_UNAVAILABLE',
  RESCHEDULE_REQUESTED: 'RESCHEDULE_REQUESTED',
  INCIDENT_RAISED: 'INCIDENT_RAISED',
  RECOVERY_APPLIED: 'RECOVERY_APPLIED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  FEEDBACK_REQUESTED: 'FEEDBACK_REQUESTED',
});

export const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  JOB_CREATED: 'JOB_CREATED',
  AVAILABILITY_PARSED: 'AVAILABILITY_PARSED',
  AVAILABILITY_UPDATED: 'AVAILABILITY_UPDATED',
  REQUEST_CREATED: 'REQUEST_CREATED',
  INTERVIEWERS_MATCHED: 'INTERVIEWERS_MATCHED',
  SLOTS_GENERATED: 'SLOTS_GENERATED',
  AUTO_BOOKED: 'AUTO_BOOKED',
  OFFER_SENT: 'OFFER_SENT',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_DECLINED: 'OFFER_DECLINED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  CANDIDATE_CANCELLED: 'CANDIDATE_CANCELLED',
  SLOT_RECOMMENDED: 'SLOT_RECOMMENDED',
  INTERVIEW_CREATED: 'INTERVIEW_CREATED',
  INTERVIEW_CONFIRMED: 'INTERVIEW_CONFIRMED',
  INTERVIEW_DECLINED: 'INTERVIEW_DECLINED',
  INTERVIEW_CANCELLED: 'INTERVIEW_CANCELLED',
  INTERVIEW_RESCHEDULED: 'INTERVIEW_RESCHEDULED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
  PANEL_ACCEPTED: 'PANEL_ACCEPTED',
  PANEL_DECLINED: 'PANEL_DECLINED',
  CALENDAR_EVENT_CREATED: 'CALENDAR_EVENT_CREATED',
  CALENDAR_EVENT_CANCELLED: 'CALENDAR_EVENT_CANCELLED',
  MEETING_CREATED: 'MEETING_CREATED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
  FEEDBACK_ANALYZED: 'FEEDBACK_ANALYZED',
  NEXT_ROUND_RECOMMENDED: 'NEXT_ROUND_RECOMMENDED',
  INCIDENT_DETECTED: 'INCIDENT_DETECTED',
  IMPACT_ANALYZED: 'IMPACT_ANALYZED',
  RECOVERY_PLANNED: 'RECOVERY_PLANNED',
  RECOVERY_APPLIED: 'RECOVERY_APPLIED',
  RECOVERY_APPROVED: 'RECOVERY_APPROVED',
  RECOVERY_REJECTED: 'RECOVERY_REJECTED',
  RECOVERY_FAILED: 'RECOVERY_FAILED',
  SETTING_UPDATED: 'SETTING_UPDATED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  AI_FALLBACK_USED: 'AI_FALLBACK_USED',
});

export const RECOMMENDATION = Object.freeze({
  STRONG_YES: 'STRONG_YES',
  YES: 'YES',
  NEUTRAL: 'NEUTRAL',
  NO: 'NO',
  STRONG_NO: 'STRONG_NO',
});
export const RECOMMENDATION_VALUES = Object.values(RECOMMENDATION);

/** Which interview types each round name conventionally maps to (used by seed + UI). */
export const DEFAULT_ROUND_PLAN = Object.freeze([
  { roundNumber: 1, roundName: 'Technical Screen', interviewType: 'TECHNICAL', durationMinutes: 45 },
  { roundNumber: 2, roundName: 'Coding Round', interviewType: 'CODING', durationMinutes: 60 },
  { roundNumber: 3, roundName: 'System Design', interviewType: 'SYSTEM_DESIGN', durationMinutes: 60 },
  { roundNumber: 4, roundName: 'Hiring Manager', interviewType: 'MANAGERIAL', durationMinutes: 45 },
  { roundNumber: 5, roundName: 'HR Discussion', interviewType: 'HR', durationMinutes: 30 },
]);

export const SETTING_KEYS = Object.freeze({
  DEFAULT_BUFFER_MINUTES: 'DEFAULT_BUFFER_MINUTES',
  SLOT_GRANULARITY_MINUTES: 'SLOT_GRANULARITY_MINUTES',
  DEFAULT_WORK_START_MINUTE: 'DEFAULT_WORK_START_MINUTE',
  DEFAULT_WORK_END_MINUTE: 'DEFAULT_WORK_END_MINUTE',
  AUTONOMY_AUTO_APPLY_MAX_RISK: 'AUTONOMY_AUTO_APPLY_MAX_RISK',
  MAX_PROPOSALS: 'MAX_PROPOSALS',
  PROPOSAL_TTL_HOURS: 'PROPOSAL_TTL_HOURS',
  MONITOR_ENABLED: 'MONITOR_ENABLED',
  OVERRUN_GRACE_MINUTES: 'OVERRUN_GRACE_MINUTES',
});
